
#include "opcodes.h"

const char* opcode_to_str(opcode_t type) {

    return (type == REG_R00)         ? "R0" :
            (type == REG_R01)        ? "R1" :
            (type == REG_R02)        ? "R2" :
            (type == REG_R03)        ? "R3" :
            (type == REG_R04)        ? "R4" :
            (type == REG_R05)        ? "R5" :
            (type == REG_R06)        ? "R6" :
            (type == REG_R07)        ? "R7" :
            (type == REG_R08)        ? "R8" :
            (type == REG_R09)        ? "R9" :
            (type == REG_R10)        ? "R10" :
            (type == REG_R11)        ? "R11" :
            (type == REG_R12)        ? "R12" :
            (type == REG_R13)        ? "R13" :
            (type == REG_R14)        ? "R14" :
            (type == REG_R15)        ? "R15" :
            (type == REG_R16)        ? "R16" :
            (type == REG_R17)        ? "R17" :
            (type == REG_R18)        ? "R18" :
            (type == REG_R19)        ? "R19" :
            (type == REG_R20)        ? "R20" :
            (type == REG_R21)        ? "R21" :
            (type == REG_R22)        ? "R22" :
            (type == REG_R23)        ? "R23" :
            (type == REG_R24)        ? "R24" :
            (type == REG_R25)        ? "R25" :
            (type == REG_R26)        ? "R26" :
            (type == REG_R27)        ? "R27" :
            (type == REG_R28)        ? "R28" :
            (type == REG_R29)        ? "R29" :
            (type == REG_R30)        ? "R30" :
            (type == REG_R31)        ? "R31" :
            (type == REG_SP)         ? "SP" :
            (type == REG_IP)         ? "IP" :
            (type == REG_IR00)       ? "#R0" :
            (type == REG_IR01)       ? "#R1" :
            (type == REG_IR02)       ? "#R2" :
            (type == REG_IR03)       ? "#R3" :
            (type == REG_IR04)       ? "#R4" :
            (type == REG_IR05)       ? "#R5" :
            (type == REG_IR06)       ? "#R6" :
            (type == REG_IR07)       ? "#R7" :
            (type == REG_IR08)       ? "#R8" :
            (type == REG_IR09)       ? "#R9" :
            (type == REG_IR10)       ? "#R10" :
            (type == REG_IR11)       ? "#R11" :
            (type == REG_IR12)       ? "#R12" :
            (type == REG_IR13)       ? "#R13" :
            (type == REG_IR14)       ? "#R14" :
            (type == REG_IR15)       ? "#R15" :
            (type == REG_IR16)       ? "#R16" :
            (type == REG_IR17)       ? "#R17" :
            (type == REG_IR18)       ? "#R18" :
            (type == REG_IR19)       ? "#R19" :
            (type == REG_IR20)       ? "#R20" :
            (type == REG_IR21)       ? "#R21" :
            (type == REG_IR22)       ? "#R22" :
            (type == REG_IR23)       ? "#R23" :
            (type == REG_IR24)       ? "#R24" :
            (type == REG_IR25)       ? "#R25" :
            (type == REG_IR26)       ? "#R26" :
            (type == REG_IR27)       ? "#R27" :
            (type == REG_IR28)       ? "#R28" :
            (type == REG_IR29)       ? "#R29" :
            (type == REG_IR30)       ? "#R30" :
            (type == REG_IR31)       ? "#R31" :
            (type == REG_ISP)        ? "#SP" :
            (type == REG_IIP)        ? "#IP" :
            (type == OPERAND_INT8)   ? "INT8" :
            (type == OPERAND_INT16)  ? "INT16" :
            (type == OPERAND_INT32)  ? "INT32" :
            (type == OPERAND_INT64)  ? "INT64" :
            (type == OPERAND_UINT8)  ? "UINT8" :
            (type == OPERAND_UINT16) ? "UINT16" :
            (type == OPERAND_UINT32) ? "UINT32" :
            (type == OPERAND_UINT64) ? "UINT64" :
            (type == OPERAND_ARRAY)  ? "ARRAY" :
            (type == OPERAND_FLOAT)  ? "FLOAT" :
            (type == OPERAND_STRING) ? "STRING" :
            (type == OPERAND_LABEL)  ? "LABEL" :
            (type == OPERAND_ILABEL) ? "#LABEL" :
            (type == OPERAND_REG)    ? "REG" :
            (type == OPERAND_IREG)   ? "IREG" :
            (type == SEC_NONE)       ? "NONE" :
            (type == SEC_CODE)       ? "CODE" :
            (type == SEC_DATA)       ? "DATA" :
            (type == OP_LOAD)        ? "LOAD" :
            (type == OP_STOR)        ? "STOR" :
            (type == OP_PUSH)        ? "PUSH" :
            (type == OP_POP)         ? "POP" :
            (type == OP_ADD)         ? "ADD" :
            (type == OP_SUB)         ? "SUB" :
            (type == OP_MUL)         ? "MUL" :
            (type == OP_DIV)         ? "DIV" :
            (type == OP_MOD)         ? "MOD" :
            (type == OP_ADDU)        ? "ADDU" :
            (type == OP_SUBU)        ? "SUBU" :
            (type == OP_MULU)        ? "MULU" :
            (type == OP_DIVU)        ? "DIVU" :
            (type == OP_MODU)        ? "MODU" :
            (type == OP_INC)         ? "INC" :
            (type == OP_DEC)         ? "DEC" :
            (type == OP_INCU)        ? "INCU" :
            (type == OP_DECU)        ? "DECU" :
            (type == OP_SHL)         ? "SHL" :
            (type == OP_SHR)         ? "SHR" :
            (type == OP_AND)         ? "AND" :
            (type == OP_OR)          ? "OR" :
            (type == OP_XOR)         ? "XOR" :
            (type == OP_NOT)         ? "NOT" :
            (type == OP_EQU)         ? "EQU" :
            (type == OP_EQUU)        ? "EQUU" :
            (type == OP_NEQ)         ? "NEQ" :
            (type == OP_NEQU)        ? "NEQU" :
            (type == OP_LT)          ? "LT" :
            (type == OP_LTU)         ? "LTU" :
            (type == OP_GT)          ? "GT" :
            (type == OP_GTU)         ? "GTU" :
            (type == OP_LTE)         ? "LTE" :
            (type == OP_LTEU)        ? "LTEU" :
            (type == OP_GTE)         ? "GTE" :
            (type == OP_GTEU)        ? "GTEU" :
            (type == OP_JMP)         ? "JMP" :
            (type == OP_JMPT)        ? "JMPT" :
            (type == OP_JMPF)        ? "JMPF" :
            (type == OP_JMPR)        ? "JMPR" :
            (type == OP_JMPRT)       ? "JMPRT" :
            (type == OP_JMPRF)       ? "JMPRF" :
            (type == OP_CALL)        ? "CALL" :
            (type == OP_CALLT)       ? "CALLT" :
            (type == OP_CALLF)       ? "CALLF" :
            (type == OP_CALLR)       ? "CALLR" :
            (type == OP_CALLRT)      ? "CALLRT" :
            (type == OP_CALLRF)      ? "CALLRF" :
            (type == OP_RET)         ? "RET" :
            (type == OP_RETT)        ? "RETT" :
            (type == OP_RETF)        ? "RETF" :
            (type == OP_EXTERN)      ? "EXTERN" :
            (type == OP_LINK)        ? "LINK" :
            (type == OP_CLRT)        ? "CLRT" :
            (type == OP_SETT)        ? "SETT" :
            (type == OP_EXIT)        ? "EXIT" :
            (type == OP_ABORT)       ? "ABORT" :
            (type == OP_NOP)         ? "NOP" :
                                       "UNKNOWN";
}
